name: 构建部署
on:
  schedule:
    - cron: "0 */8 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write # 添加这个权限配置

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # 添加这个配置

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 8

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          touch .nojekyll 

      # 添加这个检查步骤
      - name: 检查构建输出
        run: ls -la ./docs/vitepress/dist
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/vitepress/dist
          publish_branch: gh-pages
          force_orphan: true # 添加这个配置
